# easiest makefile ever
# TODO: change this, final solution will run in same directory as all csv files
run:
	./lab3b solutions/
check: run
	diff ./solutions/lab3b_check.txt lab3_check.txt

.PHONY: run check
